apiVersion: apps/v1
kind: Deployment
metadata:
  name: lomonosov
  labels:
    app: lomonosov
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lomonosov
  template:
    metadata:
      labels:
        app: lomonosov
    spec:
      containers:
      - name: lomonosov
        image: lomonosov:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7777
        env:
        - name: PORT
          value: "7777"

